# Generated by Django 5.1.6 on 2025-03-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
    ]
